add support Ubuntu / CentOS still on-going

diff --git a/netcheck b/netcheck
--- a/netcheck
+++ b/netcheck
@@ -1,7 +1,4 @@
 #!/bin/bash
-#Author spawN
-#spawn@namek.fr
-#Creation 21.01.18
 
 #Gathering Network informations about your installation
 
@@ -13,42 +10,58 @@ if [ $EUID -ne 0 ]; then
         exit 126
 fi
 
-
 #Second : The Variables
 
-ippub=`curl -s ifconfig.ovh`
-eth4=`ip -o -4 a | awk '{print $2}' | sed -e "1d"  | sed /^$/d | while read eth; do ip -o -4 a show $eth;done | awk '{print $2,$4}' | sort -u`
-eth6=`ip -o -6 a | awk '{print $2}' | sed -e "1d"  | sed /^$/d | while read eth; do ip -o -6 a show $eth;done | awk '{print $2,$4}' | sort -u`
-netadp=`ip -o -4 a | awk '{print $2}' | sed -e "1d"  | sed /^$/d | sort -u`
-release=`lsb_release -i | awk '{print $3}'`
-version=`lsb_release -r | awk '{print $2}'`
-
+ippub=$(curl -s ifconfig.ovh)
+eth4=$(ip -o -4 a | awk '{print $2}' | sed -e "1d"  | sed /^$/d | while read eth; do ip -o -4 a show $eth;done | awk '{print $2,$4}' | sort -u)
+eth6=$(ip -o -6 a | awk '{print $2}' | sed -e "1d"  | sed /^$/d | while read eth; do ip -o -6 a show $eth;done | awk '{print $2,$4}' | sort -u)
+netadp=$(ip -o -4 a | awk '{print $2}' | sed -e "1d"  | sed /^$/d | sort -u)
+release=$(lsb_release -i | awk '{print $3}')
+version=$(lsb_release -r | awk '{print $2}')
 
 #Third : Scipt Beginning
 
 #Check if ethtool is installed
 
-if [ "$release" = "Debian" ];
-	then echo "##### We are on a $release $version #####"
-elif [ "$release" = "Fedora" ]
-	then echo "##### We are on a $release $version #####"
-echo ""
-fi
-
 case $release in
 		"Debian")
-				debethtool="dpkg -l | grep 'ethtool' | grep ii"
+				debethtool=`dpkg -l | grep 'ethtool' | grep ii`
 				if [ -z "$debethtool" ] ; then echo -e "\nPackage 'ethtool' is not installed, please install it to continue"; exit 1 ; fi
 				;;
 		"Fedora")
 				fedethtool=`dnf list --installed | grep 'ethtool.x86_64'`
 				if [ -z "$fedethtool" ] ; then echo -e "\nPackage 'ethtool' is not installed, please install it to continue"; exit 1 ;fi
 				;;
+		"CentOS")
+				cenethtool=`yum list installed | grep 'ethtool.x86_64'`
+				if [ -z "$cenethtool" ] ; then echo -e "\nPackage 'ethtool' is not installed, please install it to continue"; exit 1 ;fi
+				;;
+		"Ubuntu")
+				ubunethtool=`dpkg -l | grep 'ethtool' | grep ii`
+				if [ -z "$ubunethtool" ] ; then echo -e "\nPackage 'ethtool' is not installed, please install it to continue"; exit 1 ;fi
+				;;
 		*)
 				echo "Distro not supported by this script"
 				exit 1
 				;;
 esac
+
+#A bit of clean up
+clear
+
+echo ""
+
+if [ "$release" = "Debian" ];
+	then echo "##### We are on a $release $version #####"
+elif [ "$release" = "Fedora" ];
+	then echo "##### We are on a $release $version #####"
+elif [ "$release" = "CentOS" ];
+	then echo "##### We are on a $release $version #####"
+elif [ "$release" = "Ubuntu" ];
+	then echo "##### We are on a $release $version #####"
+elif [ "$release" = "127" ];
+	then echo "##### Cannot identify the distro -- Please try to install lsb_release package #####"
+fi
 
 echo ""
 
